### PR TITLE
Fix empty languages repos

### PR DESCRIPTION
**Pull request by AmirAhrari**
If the repository contains no language do not display language label

### CODE REVIEW

**Comment by hashirshoaeb** [comment]
Hi @AmirAhrari 

I'm handling new issues and bug fixes in [new-features](https://github.com/hashirshoaeb/home/tree/new-features) branch. Feel free to contribute there. 💯 

Happy Coding 
Hashir

**Comment by hashirshoaeb** [comment]
There were many issues that has been fixed by @telriot . I really appreciate if look into [new-features](https://github.com/hashirshoaeb/home/tree/new-features) branch.

**Comment by hashirshoaeb** [comment]
Changing the base branch is creating conflicts. 

- Try, pulling new-features branch.
- Test it locally
- make new changes
- open pull request

Thanks,
Hashir

**Comment by telriot** [comment]
Will give it a look ASAP!

**Comment by hashirshoaeb** [comment]
Hi @AmirAhrari 

Seems like you are not working on this. Looking forward to hear from you. :)

Hashir

**Pull request closed without merging**
