### PR TITLE
New functions and code refactor

### PR DESCRIPTION
**Pull request by telriot**
Hi there!

Took care of essentially everything we discussed except from the dark-mode.
Please check the new features out and let me know whether it feels alright. Changing details son't be a problem.
I cleaned up the code quite a bit, split some components in several parts, added react-bootstrap and node-sass to the dependencies. I was thinking of getting rid of jQuery since we are not using boostrap features other than classes anymore (as we should not anyway in React).
I also fixed some spelling typos and the alerts from React.
The code is now easier to work on, and there is a door open for customizing bootstrap in a clean way that was not there before.

Have a great day and hear from you soon!

Ben

### CODE REVIEW

**Comment by hashirshoaeb** [comment]
- Font size at phone sized screen is perfect. ❤️ 
- However, overall font size at desktop sized screen is relatively larger than it was before. (Previous one looks better)
- Same with the size of logos at full screen.
- For typist make following changes:

```diff
- <Typist className="lead typist">
+ <Typist className="lead typist" cursor={{ show: false }}>
```

```diff
- "devDesc": "| Engineer | Programmer | Web Developer | Photographer | Athlete | Artist ",
+ "devDesc": "Engineer | Programmer | Web Developer | Photographer | Athlete | Artist",
```

- Animate the skill bars, (when bars are visible on screen, it should start from 0 to max (i.e. 80)).

**Comment by hashirshoaeb** [comment]
Great @telriot ❤️ 
There are few more changes that came in my mind.

- Separate the get in touch Component from the Footer Component.
- Make the visibility of "Skills" and "Get in touch" optional. (like navbar and blog). Ask for it in configurations.json (i.e. showSkills: true)
- In configurations.json icons.id is useless, and make following change in Project.jsx
```diff
- {projectsArray.length
-            ? projectsArray.map((project) => (
-                <ProjectCard key={project.id} id={project.id} value={project} />

{projectsArray.length
            ? projectsArray.map((project, index) => (
                <ProjectCard key={index} id={index} value={project} />
```
- try removing "style": "socialicons" as well, it is linked with colour change on hover on icon.

**Comment by telriot** [comment]
Done :+1: 
Instead of just using the index for the Project.jsx key i used a semantic identifier + index.
The rest is just the way you called it.

Have a great day!

**Comment by hashirshoaeb** [comment]
Amazing @telriot. I'm so much thankful for your support and contribution. I'm merging your changes.

**Pull request merged**
