### PR TITLE
Minimalistic navbar restyle

### PR DESCRIPTION
**Pull request by telriot**
Hi there Hashir!
This is an idea for the navbar restyle you were talking about. 
There are just some small changes to make it more responsive, and to give it a cleaner feel.
I used a css module to override some of bootstrap classes, and to make it easy to refer to the changes.
Let me know if you thinik it is ok, and have a great day!

B.

### CODE REVIEW

**Comment by hashirshoaeb** [comment]
Hey @telriot I liked your work. You can make it even better.

Can you set the opacity of Navbar to zero in the start, and as on scrolling, as it crosses the MainBody, the background opacity should set (around 7 to 9), with some transition time.
   
Have a look into this [link](https://codepen.io/sonorangirl/pen/XmRBjq).

**Comment by hashirshoaeb** [comment]
Also can you add the semicolons back?

**Comment by hashirshoaeb** [comment]
I have tried this, check this how it looks. 
```css
.navbarTransparent {
  background-color: rgba(255, 255, 255, 0);
  transition: background-color 0.2s;
}
.navbarWhite {
  background-color: rgba(234, 236, 239, 0.81);
  transition: background-color 0.2s;
}
```
```css
.brand {
  color: #363636 !important;
}

```

**Comment by telriot** [comment]
Hey there :)

Looks good to me, I have updated the colors.
The thing with keeping the navbar transparent for the whole intro section
is that when the screen gets smaller the brand and the main text end up
conflicting. That is why I thought that getting a bg color soon after
leaving the top would help visualization, even though I understand it looks
cool without any bg.
To be honest, I was thinking of making it have a bg even before the present
breakpoint.

Still, if you want to go for the full transparent look, to make the navbar
change once we get past the intro section I will need to add a few things
to the app, since the section size is not fixed.
Please let me know what your ideas are, and have a great day!

B.

**Comment by telriot** [comment]
And sorry: what semicolons? :D

**Comment by hashirshoaeb** [comment]
> And sorry: what semicolons? :D 
```js
  ;
```

**Comment by telriot** [comment]
Yep, I know we were talking about semicolons, but I was wondering where
exactly.
Thinking about it now it could just be some automatic linting from my
editor. It removes them automatically wherever I work on a file.
If it is a problem I will change the settings and resave!

**Comment by hashirshoaeb** [comment]
Seems better now. Right?

**Comment by hashirshoaeb** [comment]
> Hey there :) Looks good to me, I have updated the colors. The thing with keeping the navbar transparent for the whole intro section is that when the screen gets smaller the brand and the main text end up conflicting. That is why I thought that getting a bg color soon after leaving the top would help visualization, even though I understand it looks cool without any bg. To be honest, I was thinking of making it have a bg even before the present breakpoint. Still, if you want to go for the full transparent look, to make the navbar change once we get past the intro section I will need to add a few things to the app, since the section size is not fixed. Please let me know what your ideas are, and have a great day! B.

Hmm, what we can do is. In the start Navbar should remain transparent and we change the transparency when it reaches "name" in the MainBody. What do you say?

**Comment by telriot** [comment]
So, the changes are there: the navbar is only transparent when its div does
not overlap with the main body title, and this behavior works both when
toggled and not toggled.
I added two hooks to your app (you will find them in the hook folder), one
that substitutes the previous scroll listener, and the other that takes
care of properly rendering the color of the navbar on toggle.

You will also find that I had to pass around the main body title ref in
order to have it in Navbar. Since there is no context, and there is not
much state management going on in the app, I think that just hooking it up
like that is the simplest decision, at the moment.
Please check for performance issues, even though there should not be any.
I will take another look at the whole later and maybe refactor a bit.

Have a great day!

B.

**Pull request closed without merging**
