### PR TITLE
Added Experience Section in Project

### PR DESCRIPTION
**Pull request by 1hanzla100**
Successfully Added Experience Section in project

### CODE REVIEW

**Comment by 1hanzla100** [comment]
Kindky Merge My Pull Request

**Comment by 1hanzla100** [comment]
https://user-images.githubusercontent.com/59178380/104150173-d7a86980-53fa-11eb-83a0-a1b859dae1cd.mp4

**Comment by 1hanzla100** [comment]
@hashirshoaeb If there is not issues in Experience Section Kindly Merge it with master branch

**Review by hashirshoaeb — APPROVED** [review]

**Comment by hashirshoaeb** [comment]
Thank you for contributing. and sorry for making you wait this long.🔥

**Pull request merged**
